from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    IO_READ_FAILED = "ZE-IO-READ-FAILED"

    UNS_EXTRA_MISSING = "ZE-UNS-EXTRA-MISSING"
    UNS_PARTITION_FAILED = "ZE-UNS-PARTITION-FAILED"
    UNS_UNSUPPORTED_TYPE = "ZE-UNS-UNSUPPORTED-TYPE"

    # Delivery (destinations / replay)
    DELIVERY_FAILED = "ZE-DELIVERY-FAILED"
    DELIVERY_HTTP_FAILED = "ZE-DELIVERY-HTTP-FAILED"
    DELIVERY_KAFKA_FAILED = "ZE-DELIVERY-KAFKA-FAILED"
    DELIVERY_WEAVIATE_FAILED = "ZE-DELIVERY-WEAVIATE-FAILED"
    DELIVERY_INVALID_PAYLOAD = "ZE-DELIVERY-INVALID-PAYLOAD"
