from typing import Mapping, Sequence

class KafkaError:
    ...

class Message:
    def error(self) -> KafkaError | None: ...
    def value(self) -> bytes | None: ...
    def key(self) -> bytes | None: ...

class Producer:
    def __init__(self, config: Mapping[str, object]) -> None: ...
    def produce(self, topic: str, *, value: bytes | None = ..., key: bytes | None = ...) -> None: ...
    def flush(self, timeout: float = ...) -> int: ...

class Consumer:
    def __init__(self, config: Mapping[str, object]) -> None: ...
    def subscribe(self, topics: Sequence[str]) -> None: ...
    def poll(self, timeout: float = ...) -> Message | None: ...
    def close(self) -> None: ...
