from __future__ import annotations

# Stub generated by tools/rewrite_uns_stream_partition_stubs.py
# pyright: reportUnusedFunction=false
from typing import Any, NoReturn


def partition_api(*args: Any, **kwargs: Any) -> NoReturn:
    """Placeholder for uns_stream.partition.api.partition_api.

    This function will be implemented incrementally.
    """
    raise NotImplementedError("uns_stream.partition.api.partition_api is not implemented yet.")
