from __future__ import annotations

from pathlib import Path
from typing import Mapping

from uns_stream._internal.enhanced_partition import UNSET_PARTITION_OPTION
from uns_stream.backends.base import PartitionBackend
from uns_stream.service import partition_file
from zephyr_core import ErrorCode, PartitionResult, PartitionStrategy, ZephyrError

# _ROUTER: dict[str, Callable[..., PartitionResult]] = {
#     ".txt": partition_text,
#     ".text": partition_text,
#     ".log": partition_text,
#     ".html": partition_html,
#     ".htm": partition_html,
#     ".xml": partition_xml,
#     ".eml": partition_email,
#     ".msg": partition_msg,
#     ".json": partition_json,
#     ".md": partition_md,
#     ".markdown": partition_md,
#     ".pdf": partition_pdf,
#     ".png": partition_image,
#     ".jpg": partition_image,
#     ".jpeg": partition_image,
#     ".tiff": partition_image,
#     ".tif": partition_image,
#     ".bmp": partition_image,
#     ".heic": partition_image,
#     ".csv": partition_csv,
#     ".tsv": partition_tsv,
#     ".xlsx": partition_xlsx,
#     ".xls": partition_xlsx,
#     ".ndjson": partition_ndjson,
#     ".jsonl": partition_ndjson,
#     ".doc": partition_doc,
#     ".docx": partition_docx,
#     ".ppt": partition_ppt,
#     ".pptx": partition_pptx,
#     ".rtf": partition_rtf,
#     ".rst": partition_rst,
#     ".epub": partition_epub,
#     ".odt": partition_odt,
#     ".org": partition_org,
#     # 后续继续添加其他格式
# }

_KIND_BY_EXT: dict[str, str] = {
    ".txt": "text",
    ".text": "text",
    ".log": "text",
    ".html": "html",
    ".htm": "html",
    ".xml": "xml",
    ".eml": "email",
    ".msg": "msg",
    ".json": "json",
    ".md": "md",
    ".markdown": "md",
    ".pdf": "pdf",
    ".png": "image",
    ".jpg": "image",
    ".jpeg": "image",
    ".tiff": "image",
    ".tif": "image",
    ".bmp": "image",
    ".heic": "image",
    ".csv": "csv",
    ".tsv": "tsv",
    ".xlsx": "xlsx",
    ".xls": "xlsx",
    ".ndjson": "ndjson",
    ".jsonl": "ndjson",
    ".doc": "doc",
    ".docx": "docx",
    ".ppt": "ppt",
    ".pptx": "pptx",
    ".rtf": "rtf",
    ".rst": "rst",
    ".epub": "epub",
    ".odt": "odt",
    ".org": "org",
}


def partition(
    *,
    filename: str,
    strategy: PartitionStrategy | None = None,
    unique_element_ids: bool = True,
    backend: PartitionBackend | None = None,
    run_id: str | None = None,
    pipeline_version: str | None = None,
    sha256: str | None = None,
    size_bytes: int | None = None,
    profile: str | None = None,
    languages: object = UNSET_PARTITION_OPTION,
    detect_language_per_element: object = UNSET_PARTITION_OPTION,
    language_fallback: object = UNSET_PARTITION_OPTION,
    skip_infer_table_types: object = UNSET_PARTITION_OPTION,
    infer_table_structure: object = UNSET_PARTITION_OPTION,
    pdf_infer_table_structure: object = UNSET_PARTITION_OPTION,
    extract_image_block_types: object = UNSET_PARTITION_OPTION,
    extract_image_block_output_dir: object = UNSET_PARTITION_OPTION,
    extract_image_block_to_payload: object = UNSET_PARTITION_OPTION,
    data_source_metadata: object = UNSET_PARTITION_OPTION,
    metadata_filename: object = UNSET_PARTITION_OPTION,
    hi_res_model_name: object = UNSET_PARTITION_OPTION,
    model_name: object = UNSET_PARTITION_OPTION,
    starting_page_number: object = UNSET_PARTITION_OPTION,
    ocr_agent: object = UNSET_PARTITION_OPTION,
    table_ocr_agent: object = UNSET_PARTITION_OPTION,
    extra_partition_kwargs: Mapping[str, object] | None = None,
) -> PartitionResult:
    ext = Path(filename).suffix.lower()
    kind = _KIND_BY_EXT.get(ext)
    if kind is None:
        raise ZephyrError(
            code=ErrorCode.UNS_UNSUPPORTED_TYPE,
            message=f"Unsupported file extension: {ext}",
            details={"filename": filename, "ext": ext},
        )

    # mypy/pyright: _ROUTER values are callables (kept as object to avoid Protocol variance noise)
    return partition_file(
        filename=filename,
        kind=kind,
        strategy=strategy,
        unique_element_ids=unique_element_ids,
        backend=backend,
        run_id=run_id,
        pipeline_version=pipeline_version,
        sha256=sha256,
        size_bytes=size_bytes,
        profile=profile,
        languages=languages,
        detect_language_per_element=detect_language_per_element,
        language_fallback=language_fallback,
        skip_infer_table_types=skip_infer_table_types,
        infer_table_structure=infer_table_structure,
        pdf_infer_table_structure=pdf_infer_table_structure,
        extract_image_block_types=extract_image_block_types,
        extract_image_block_output_dir=extract_image_block_output_dir,
        extract_image_block_to_payload=extract_image_block_to_payload,
        data_source_metadata=data_source_metadata,
        metadata_filename=metadata_filename,
        hi_res_model_name=hi_res_model_name,
        model_name=model_name,
        starting_page_number=starting_page_number,
        ocr_agent=ocr_agent,
        table_ocr_agent=table_ocr_agent,
        extra_partition_kwargs=extra_partition_kwargs,
    )
