from __future__ import annotations

# Stub generated by tools/gen_uns_stream_partition_stubs.py


def _not_implemented() -> None:
    raise NotImplementedError("uns_stream.partition.pptx is not implemented yet.")
