from __future__ import annotations

# Stub generated by tools/rewrite_uns_stream_partition_stubs.py
# pyright: reportUnusedFunction=false
from typing import Any, NoReturn


def partition_rtf(*args: Any, **kwargs: Any) -> NoReturn:
    """Placeholder for uns_stream.partition.rtf.partition_rtf.

    This function will be implemented incrementally.
    """
    raise NotImplementedError("uns_stream.partition.rtf.partition_rtf is not implemented yet.")
