from __future__ import annotations

from pathlib import Path

MODULES = [
    "api",
    "audio",
    "auto",
    "csv",
    "doc",
    "docx",
    "email",
    "epub",
    "image",
    "json",
    "md",
    "model_init",
    "msg",
    "ndjson",
    "odt",
    "org",
    "pdf",
    "ppt",
    "pptx",
    "rst",
    "rtf",
    "strategies",
    "text",
    "text_type",
    "tsv",
    "xlsx",
    "xml",
]

BASE = Path("packages/uns-stream/src/uns_stream/partition")
BASE.mkdir(parents=True, exist_ok=True)

for m in MODULES:
    p = BASE / f"{m}.py"
    if p.exists():
        continue
    p.write_text(
        f"""from __future__ import annotations

# Stub generated by tools/gen_uns_stream_partition_stubs.py

def _not_implemented() -> None:
    raise NotImplementedError("uns_stream.partition.{m} is not implemented yet.")
""",
        encoding="utf-8",
    )
print("Generated stubs:", len([m for m in MODULES if (BASE / f"{m}.py").exists()]))
