# tools/rewrite_uns_stream_partition_stubs.py
from __future__ import annotations

from pathlib import Path

PARTITION_DIR = Path("packages/uns-stream/src/uns_stream/partition")

# 你的目录里目前包含这些文件名（从 GitHub 列表看齐）
# 这里脚本不需要写死列表：直接遍历 *.py 即可。
SPECIAL_FUNCNAME = {
    "auto": "partition",  # 你希望对外是 uns_stream.partition.auto.partition
}


def func_name(module: str) -> str:
    return SPECIAL_FUNCNAME.get(module, f"partition_{module}")


TEMPLATE = """\
from __future__ import annotations

# Stub generated by tools/rewrite_uns_stream_partition_stubs.py
# pyright: reportUnusedFunction=false

from typing import Any, NoReturn


def {fn}(*args: Any, **kwargs: Any) -> NoReturn:
    \"\"\"Placeholder for uns_stream.partition.{module}.{fn}.

    This function will be implemented incrementally.
    \"\"\"
    raise NotImplementedError("uns_stream.partition.{module}.{fn} is not implemented yet.")
"""


def main() -> None:
    if not PARTITION_DIR.exists():
        raise SystemExit(f"Partition dir not found: {PARTITION_DIR}")

    for path in sorted(PARTITION_DIR.glob("*.py")):
        module = path.stem
        # 不重写 __init__.py（保留你的包导出逻辑）
        if module == "__init__":
            continue

        fn = func_name(module)
        path.write_text(TEMPLATE.format(module=module, fn=fn), encoding="utf-8")

    print("Rewrote stubs in:", PARTITION_DIR)


if __name__ == "__main__":
    main()
