from __future__ import annotations

from zephyr_ingest.config.constants import UNS_API_KEY_ENV_NAMES, WEAVIATE_API_KEY_ENV_NAMES
from zephyr_ingest.spec.types import ConnectorSpecV1

_REGISTRY: dict[str, ConnectorSpecV1] = {
    "backend.uns_api.v1": {
        "id": "backend.uns_api.v1",
        "version": 1,
        "kind": "backend",
        "name": "Unstructured API backend",
        "description": "Send partition requests to an Unstructured API server.",
        "fields": [
            {
                "name": "backend.kind",
                "type": "string",
                "required": True,
                "default": "local",
                "cli_flags": ["--backend"],
                "choices": ["local", "uns-api"],
                "help": "Backend kind: local or uns-api.",
                "examples": ["uns-api"],
            },
            {
                "name": "backend.url",
                "type": "string",
                "required": False,
                "default": "http://localhost:8001/general/v0/general",
                "cli_flags": ["--uns-api-url"],
                "help": "Unstructured API endpoint URL.",
            },
            {
                "name": "backend.timeout_s",
                "type": "float",
                "required": False,
                "default": 60.0,
                "cli_flags": ["--uns-api-timeout-s"],
                "help": "Unstructured API request timeout (seconds).",
            },
            {
                "name": "backend.api_key",
                "type": "string",
                "required": False,
                "secret": True,
                "cli_flags": ["--uns-api-key"],
                "env_names": list(UNS_API_KEY_ENV_NAMES),
                "help": "Unstructured API key. Prefer ENV injection.",
            },
        ],
    },
    "destination.webhook.v1": {
        "id": "destination.webhook.v1",
        "version": 1,
        "kind": "destination",
        "name": "Webhook destination",
        "description": "POST DeliveryPayloadV1 to an HTTP endpoint.",
        "fields": [
            {
                "name": "destinations.webhook.url",
                "type": "string",
                "required": True,
                "cli_flags": ["--webhook-url"],
                "help": "Webhook URL (enables destination).",
            },
            {
                "name": "destinations.webhook.timeout_s",
                "type": "float",
                "required": False,
                "default": 10.0,
                "cli_flags": ["--webhook-timeout-s"],
                "help": "Webhook request timeout (seconds).",
            },
            {
                "name": "destinations.webhook.max_inflight",
                "type": "int",
                "required": False,
                "cli_flags": ["--webhook-max-inflight"],
                "help": "Webhook max inflight deliveries.",
            },
            {
                "name": "destinations.webhook.rate_limit",
                "type": "float",
                "required": False,
                "cli_flags": ["--webhook-rate-limit"],
                "help": "Webhook delivery rate limit.",
            },
        ],
    },
    "destination.kafka.v1": {
        "id": "destination.kafka.v1",
        "version": 1,
        "kind": "destination",
        "name": "Kafka destination",
        "description": "Publish DeliveryPayloadV1 to a Kafka topic.",
        "fields": [
            {
                "name": "destinations.kafka.topic",
                "type": "string",
                "required": True,
                "cli_flags": ["--kafka-topic"],
                "help": "Kafka topic name (requires --kafka-brokers).",
            },
            {
                "name": "destinations.kafka.brokers",
                "type": "string",
                "required": True,
                "cli_flags": ["--kafka-brokers"],
                "help": "Kafka broker addresses, comma-separated (e.g. localhost:9092)",
                "examples": ["localhost:9092"],
            },
            {
                "name": "destinations.kafka.flush_timeout_s",
                "type": "float",
                "required": False,
                "default": 10.0,
                "cli_flags": ["--kafka-flush-timeout-s"],
                "help": "Kafka producer flush timeout in seconds.",
            },
            {
                "name": "destinations.kafka.max_inflight",
                "type": "int",
                "required": False,
                "cli_flags": ["--kafka-max-inflight"],
                "help": "Kafka max inflight deliveries.",
            },
            {
                "name": "destinations.kafka.rate_limit",
                "type": "float",
                "required": False,
                "cli_flags": ["--kafka-rate-limit"],
                "help": "Kafka delivery rate limit.",
            },
        ],
    },
    "destination.weaviate.v1": {
        "id": "destination.weaviate.v1",
        "version": 1,
        "kind": "destination",
        "name": "Weaviate destination",
        "description": "Insert/replace 1 Zephyr document as 1 "
        "Weaviate object using a deterministic UUID.",
        "fields": [
            {
                "name": "destinations.weaviate.collection",
                "type": "string",
                "required": True,
                "cli_flags": ["--weaviate-collection"],
                "help": "Weaviate collection name (enables destination).",
            },
            {
                "name": "destinations.weaviate.max_batch_errors",
                "type": "int",
                "required": False,
                "default": 0,
                "cli_flags": ["--weaviate-max-batch-errors"],
                "help": "Max tolerated batch errors; 0 means any error fails delivery (default: 0)",
            },
            {
                "name": "destinations.weaviate.timeout_s",
                "type": "float",
                "required": False,
                "cli_flags": ["--weaviate-timeout-s"],
                "help": "Weaviate request timeout in seconds.",
            },
            {
                "name": "destinations.weaviate.max_inflight",
                "type": "int",
                "required": False,
                "cli_flags": ["--weaviate-max-inflight"],
                "help": "Weaviate max inflight deliveries.",
            },
            {
                "name": "destinations.weaviate.rate_limit",
                "type": "float",
                "required": False,
                "cli_flags": ["--weaviate-rate-limit"],
                "help": "Weaviate delivery rate limit.",
            },
            {
                "name": "destinations.weaviate.http_host",
                "type": "string",
                "required": False,
                "default": "localhost",
                "cli_flags": ["--weaviate-http-host"],
            },
            {
                "name": "destinations.weaviate.http_port",
                "type": "int",
                "required": False,
                "default": 8080,
                "cli_flags": ["--weaviate-http-port"],
            },
            {
                "name": "destinations.weaviate.http_secure",
                "type": "bool",
                "required": False,
                "default": False,
                "cli_flags": ["--weaviate-http-secure"],
            },
            {
                "name": "destinations.weaviate.grpc_host",
                "type": "string",
                "required": False,
                "default": "localhost",
                "cli_flags": ["--weaviate-grpc-host"],
            },
            {
                "name": "destinations.weaviate.grpc_port",
                "type": "int",
                "required": False,
                "default": 50051,
                "cli_flags": ["--weaviate-grpc-port"],
            },
            {
                "name": "destinations.weaviate.grpc_secure",
                "type": "bool",
                "required": False,
                "default": False,
                "cli_flags": ["--weaviate-grpc-secure"],
            },
            {
                "name": "destinations.weaviate.skip_init_checks",
                "type": "bool",
                "required": False,
                "default": False,
                "cli_flags": ["--weaviate-skip-init-checks"],
            },
            {
                "name": "destinations.weaviate.api_key",
                "type": "string",
                "required": False,
                "secret": True,
                "cli_flags": ["--weaviate-api-key"],
                "env_names": list(WEAVIATE_API_KEY_ENV_NAMES),
                "help": "Weaviate API key. Prefer ENV injection.",
            },
        ],
    },
    "destination.s3.v1": {
        "id": "destination.s3.v1",
        "version": 1,
        "kind": "destination",
        "name": "S3-compatible destination",
        "description": "Write DeliveryPayloadV1 as one JSON object to an S3-compatible bucket.",
        "fields": [
            {
                "name": "destinations.s3.bucket",
                "type": "string",
                "required": True,
                "cli_flags": ["--s3-bucket"],
                "help": "S3-compatible bucket/container name.",
            },
            {
                "name": "destinations.s3.region",
                "type": "string",
                "required": True,
                "cli_flags": ["--s3-region"],
                "help": "S3-compatible region name.",
            },
            {
                "name": "destinations.s3.access_key",
                "type": "string",
                "required": True,
                "secret": True,
                "cli_flags": ["--s3-access-key"],
                "help": "S3-compatible access key.",
            },
            {
                "name": "destinations.s3.secret_key",
                "type": "string",
                "required": True,
                "secret": True,
                "cli_flags": ["--s3-secret-key"],
                "help": "S3-compatible secret key.",
            },
            {
                "name": "destinations.s3.endpoint_url",
                "type": "string",
                "required": False,
                "cli_flags": ["--s3-endpoint-url"],
                "help": "Optional custom S3-compatible endpoint URL.",
            },
            {
                "name": "destinations.s3.session_token",
                "type": "string",
                "required": False,
                "secret": True,
                "cli_flags": ["--s3-session-token"],
                "help": "Optional S3-compatible session token.",
            },
            {
                "name": "destinations.s3.prefix",
                "type": "string",
                "required": False,
                "default": "",
                "cli_flags": ["--s3-prefix"],
                "help": "Object key prefix for delivered payloads.",
            },
            {
                "name": "destinations.s3.write_mode",
                "type": "string",
                "required": False,
                "default": "overwrite",
                "choices": ["overwrite"],
                "cli_flags": ["--s3-write-mode"],
                "help": "Delivery write mode for the S3-compatible destination.",
            },
            {
                "name": "destinations.s3.max_inflight",
                "type": "int",
                "required": False,
                "cli_flags": ["--s3-max-inflight"],
                "help": "S3 destination max inflight deliveries.",
            },
            {
                "name": "destinations.s3.rate_limit",
                "type": "float",
                "required": False,
                "cli_flags": ["--s3-rate-limit"],
                "help": "S3 destination delivery rate limit.",
            },
        ],
    },
    "destination.opensearch.v1": {
        "id": "destination.opensearch.v1",
        "version": 1,
        "kind": "destination",
        "name": "OpenSearch destination",
        "description": "Index DeliveryPayloadV1 into an OpenSearch-compatible index.",
        "fields": [
            {
                "name": "destinations.opensearch.url",
                "type": "string",
                "required": True,
                "cli_flags": ["--opensearch-url"],
                "help": "OpenSearch base URL.",
            },
            {
                "name": "destinations.opensearch.index",
                "type": "string",
                "required": True,
                "cli_flags": ["--opensearch-index"],
                "help": "OpenSearch index name.",
            },
            {
                "name": "destinations.opensearch.timeout_s",
                "type": "float",
                "required": False,
                "default": 10.0,
                "cli_flags": ["--opensearch-timeout-s"],
                "help": "OpenSearch request timeout in seconds.",
            },
            {
                "name": "destinations.opensearch.skip_tls_verify",
                "type": "bool",
                "required": False,
                "default": False,
                "cli_flags": ["--opensearch-skip-tls-verify"],
                "help": "Disable TLS certificate verification for OpenSearch.",
            },
            {
                "name": "destinations.opensearch.username",
                "type": "string",
                "required": False,
                "cli_flags": ["--opensearch-username"],
                "help": "Optional OpenSearch username.",
            },
            {
                "name": "destinations.opensearch.password",
                "type": "string",
                "required": False,
                "secret": True,
                "cli_flags": ["--opensearch-password"],
                "help": "Optional OpenSearch password.",
            },
            {
                "name": "destinations.opensearch.max_inflight",
                "type": "int",
                "required": False,
                "cli_flags": ["--opensearch-max-inflight"],
                "help": "OpenSearch max inflight deliveries.",
            },
            {
                "name": "destinations.opensearch.rate_limit",
                "type": "float",
                "required": False,
                "cli_flags": ["--opensearch-rate-limit"],
                "help": "OpenSearch delivery rate limit.",
            },
        ],
    },
    "destination.clickhouse.v1": {
        "id": "destination.clickhouse.v1",
        "version": 1,
        "kind": "destination",
        "name": "ClickHouse destination",
        "description": "Write DeliveryPayloadV1 rows into ClickHouse over HTTP.",
        "fields": [
            {
                "name": "destinations.clickhouse.url",
                "type": "string",
                "required": True,
                "cli_flags": ["--clickhouse-url"],
                "help": "ClickHouse HTTP endpoint URL.",
            },
            {
                "name": "destinations.clickhouse.table",
                "type": "string",
                "required": True,
                "cli_flags": ["--clickhouse-table"],
                "help": "ClickHouse target table name.",
            },
            {
                "name": "destinations.clickhouse.timeout_s",
                "type": "float",
                "required": False,
                "default": 10.0,
                "cli_flags": ["--clickhouse-timeout-s"],
                "help": "ClickHouse request timeout in seconds.",
            },
            {
                "name": "destinations.clickhouse.database",
                "type": "string",
                "required": False,
                "cli_flags": ["--clickhouse-database"],
                "help": "Optional ClickHouse database name.",
            },
            {
                "name": "destinations.clickhouse.username",
                "type": "string",
                "required": False,
                "cli_flags": ["--clickhouse-username"],
                "help": "Optional ClickHouse username.",
            },
            {
                "name": "destinations.clickhouse.password",
                "type": "string",
                "required": False,
                "secret": True,
                "cli_flags": ["--clickhouse-password"],
                "help": "Optional ClickHouse password.",
            },
            {
                "name": "destinations.clickhouse.max_inflight",
                "type": "int",
                "required": False,
                "cli_flags": ["--clickhouse-max-inflight"],
                "help": "ClickHouse max inflight deliveries.",
            },
            {
                "name": "destinations.clickhouse.rate_limit",
                "type": "float",
                "required": False,
                "cli_flags": ["--clickhouse-rate-limit"],
                "help": "ClickHouse delivery rate limit.",
            },
        ],
    },
    "destination.mongodb.v1": {
        "id": "destination.mongodb.v1",
        "version": 1,
        "kind": "destination",
        "name": "MongoDB-compatible destination",
        "description": "Replace/upsert one DeliveryPayloadV1 document into a MongoDB-compatible "
        "collection using a deterministic _id.",
        "fields": [
            {
                "name": "destinations.mongodb.uri",
                "type": "string",
                "required": True,
                "cli_flags": ["--mongodb-uri"],
                "help": "MongoDB connection URI.",
            },
            {
                "name": "destinations.mongodb.database",
                "type": "string",
                "required": True,
                "cli_flags": ["--mongodb-database"],
                "help": "MongoDB database name.",
            },
            {
                "name": "destinations.mongodb.collection",
                "type": "string",
                "required": True,
                "cli_flags": ["--mongodb-collection"],
                "help": "MongoDB collection name.",
            },
            {
                "name": "destinations.mongodb.timeout_s",
                "type": "float",
                "required": False,
                "default": 10.0,
                "cli_flags": ["--mongodb-timeout-s"],
                "help": "MongoDB server selection timeout in seconds.",
            },
            {
                "name": "destinations.mongodb.write_mode",
                "type": "string",
                "required": False,
                "default": "replace_upsert",
                "choices": ["replace_upsert"],
                "cli_flags": ["--mongodb-write-mode"],
                "help": "MongoDB write mode for this bounded subset.",
            },
            {
                "name": "destinations.mongodb.username",
                "type": "string",
                "required": False,
                "cli_flags": ["--mongodb-username"],
                "help": "MongoDB username (requires --mongodb-password).",
            },
            {
                "name": "destinations.mongodb.password",
                "type": "string",
                "required": False,
                "secret": True,
                "cli_flags": ["--mongodb-password"],
                "help": "MongoDB password (requires --mongodb-username).",
            },
            {
                "name": "destinations.mongodb.max_inflight",
                "type": "int",
                "required": False,
                "cli_flags": ["--mongodb-max-inflight"],
                "help": "MongoDB max inflight deliveries.",
            },
            {
                "name": "destinations.mongodb.rate_limit",
                "type": "float",
                "required": False,
                "cli_flags": ["--mongodb-rate-limit"],
                "help": "MongoDB delivery rate limit.",
            },
        ],
    },
    "destination.loki.v1": {
        "id": "destination.loki.v1",
        "version": 1,
        "kind": "destination",
        "name": "Loki-compatible destination",
        "description": "Push one DeliveryPayloadV1 as one Loki-compatible log stream entry.",
        "fields": [
            {
                "name": "destinations.loki.url",
                "type": "string",
                "required": True,
                "cli_flags": ["--loki-url"],
                "help": "Loki push endpoint or base URL.",
            },
            {
                "name": "destinations.loki.stream",
                "type": "string",
                "required": True,
                "cli_flags": ["--loki-stream"],
                "help": "Static stream selector label value for this bounded Loki subset.",
            },
            {
                "name": "destinations.loki.timeout_s",
                "type": "float",
                "required": False,
                "default": 10.0,
                "cli_flags": ["--loki-timeout-s"],
                "help": "Loki request timeout in seconds.",
            },
            {
                "name": "destinations.loki.tenant_id",
                "type": "string",
                "required": False,
                "cli_flags": ["--loki-tenant-id"],
                "help": "Optional Loki tenant ID sent via X-Scope-OrgID.",
            },
            {
                "name": "destinations.loki.max_inflight",
                "type": "int",
                "required": False,
                "cli_flags": ["--loki-max-inflight"],
                "help": "Loki max inflight deliveries.",
            },
            {
                "name": "destinations.loki.rate_limit",
                "type": "float",
                "required": False,
                "cli_flags": ["--loki-rate-limit"],
                "help": "Loki delivery rate limit.",
            },
        ],
    },
    "destination.sqlite.v1": {
        "id": "destination.sqlite.v1",
        "version": 1,
        "kind": "destination",
        "name": "SQLite destination",
        "description": "Write one DeliveryPayloadV1 row into a bounded local SQLite table.",
        "fields": [
            {
                "name": "destinations.sqlite.file_path",
                "type": "string",
                "required": True,
                "cli_flags": ["--sqlite-file-path"],
                "help": "SQLite database file path.",
            },
            {
                "name": "destinations.sqlite.table_name",
                "type": "string",
                "required": False,
                "default": "zephyr_delivery_records",
                "cli_flags": ["--sqlite-table-name"],
                "help": "SQLite table name for DeliveryPayloadV1 rows.",
            },
            {
                "name": "destinations.sqlite.timeout_s",
                "type": "float",
                "required": False,
                "default": 5.0,
                "cli_flags": ["--sqlite-timeout-s"],
                "help": "SQLite connection timeout in seconds.",
            },
            {
                "name": "destinations.sqlite.mode",
                "type": "string",
                "required": False,
                "default": "replace_upsert",
                "choices": ["replace_upsert"],
                "cli_flags": ["--sqlite-mode"],
                "help": "Bounded SQLite write mode for the retained replace/upsert subset.",
            },
        ],
    },
    "source.uns.http_document.v1": {
        "id": "source.uns.http_document.v1",
        "version": 1,
        "kind": "source",
        "name": "UNS HTTP document source",
        "description": "Bounded document acquisition from an explicit HTTP document locator.",
        "fields": [],
    },
    "source.uns.s3_document.v1": {
        "id": "source.uns.s3_document.v1",
        "version": 1,
        "kind": "source",
        "name": "UNS S3-compatible document source",
        "description": "Bounded document acquisition from explicit bucket/key/version facts.",
        "fields": [],
    },
    "source.uns.git_document.v1": {
        "id": "source.uns.git_document.v1",
        "version": 1,
        "kind": "source",
        "name": "UNS Git document source",
        "description": "Bounded document acquisition from explicit repository/ref/path facts.",
        "fields": [],
    },
    "source.uns.google_drive_document.v1": {
        "id": "source.uns.google_drive_document.v1",
        "version": 1,
        "kind": "source",
        "name": "UNS Google Drive document source",
        "description": "Bounded local acquisition from explicit Drive file/revision facts.",
        "fields": [],
    },
    "source.uns.confluence_document.v1": {
        "id": "source.uns.confluence_document.v1",
        "version": 1,
        "kind": "source",
        "name": "UNS Confluence document source",
        "description": "Bounded page/content acquisition from explicit site/page/version facts.",
        "fields": [],
    },
    "source.it.http_json_cursor.v1": {
        "id": "source.it.http_json_cursor.v1",
        "version": 1,
        "kind": "source",
        "name": "IT HTTP JSON cursor source",
        "description": "Bounded structured record acquisition over explicit cursor progression.",
        "fields": [],
    },
    "source.it.postgresql_incremental.v1": {
        "id": "source.it.postgresql_incremental.v1",
        "version": 1,
        "kind": "source",
        "name": "IT PostgreSQL incremental source",
        "description": "Bounded structured row acquisition over explicit ordered progression.",
        "fields": [],
    },
    "source.it.clickhouse_incremental.v1": {
        "id": "source.it.clickhouse_incremental.v1",
        "version": 1,
        "kind": "source",
        "name": "IT ClickHouse incremental source",
        "description": "Bounded structured row acquisition over explicit query/window progression.",
        "fields": [],
    },
    "source.it.kafka_partition_offset.v1": {
        "id": "source.it.kafka_partition_offset.v1",
        "version": 1,
        "kind": "source",
        "name": "IT Kafka partition/offset source",
        "description": (
            "Bounded structured record acquisition over explicit partition/offset facts."
        ),
        "fields": [],
    },
    "source.it.mongodb_incremental.v1": {
        "id": "source.it.mongodb_incremental.v1",
        "version": 1,
        "kind": "source",
        "name": "IT MongoDB incremental source",
        "description": "Bounded structured document acquisition over explicit ordered progression.",
        "fields": [],
    },
}


def list_spec_ids() -> list[str]:
    return sorted(_REGISTRY.keys())


def get_spec(*, spec_id: str) -> ConnectorSpecV1 | None:
    return _REGISTRY.get(spec_id)
